name:        aoc
version:     0.1.0.0
synopsis:    Advent of Code 2020 solutions
description: My solutions for Advent of Code 2020, primarily in Haskell.
category:    hmm
github:      chuahou/aoc
maintainer:  Chua Hou <human+github@chuahou.dev>

ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates

default-extensions:
    - BangPatterns
    - GADTs
    - LambdaCase
    - TupleSections
    - TypeOperators

dependencies:
    - base >= 4.13 && < 5

data-files:
    - input/day*.txt
    - scripts/*.sh

library:
    source-dirs: src
    dependencies:
        - array
        - parsec
        - template-haskell
        - process >= 1.6.9.0 && < 1.7

executable:
    main:         Main.hs
    source-dirs:  exe
    dependencies:
        - aoc
